apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  pihole-password: ENC[AES256_GCM,data:hMt0ZJ+zGlA=,iv:Zm/jkif8whARniXJgztCvnQsxVx0KkjiEjVncmNl8bw=,tag:UrDxenvp4B1bHwu+4C4kiA==,type:str]
sops:
  age:
    - recipient: age1nurh0k74yrr98f0e03hnt9lx0c59la47umg7lmf774u6vyqup9dslhfkjh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5blBhL2owRktFN1Awanpw
        NWNxZkZlVmx5WUFpSGdySXJLTEhpMVVEOUhVCmZZcFIyV1lOM04zVUVVaVNYL2J6
        SXg3b3ZScG1TQXFTWkxYQy9ON3QzTXcKLS0tIGJHM3JIdTdxdys3VVdVWnBaV3hu
        Q3MvZFdUTHVGc1o3ckphR0pEZkU3WkUKlf4f7LqAqXwax300UNA4JKSWtkz1AFEf
        W7touXKYukyRsoTjks5Z9dcNpeQnhpuHsAjvD9HqVubd0bYlZizEWA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T19:20:48Z"
  mac: ENC[AES256_GCM,data:v4MWJNlNObLCvE3LAnbzq9URqaAIxK/HLwgKjIWRlx89cYsmwOcTcnLZS1t3airz7RVhHAFPN9wllZPDhEzuUezefwJ8ccXm9YD6Ac6B3YmWNVgOM82GqHkUOKOXrn/YMOOy0qTUv9QtlR/WRvPHIzaSIXzGexmSIj+U5JnDR/I=,iv:l1hoshuZcwP/IBhkpRMAecWYnrbYNsvp+1Dx/8eHgVU=,tag:w5M0xYHmeDcUNiPsYveljQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
