apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  pihole-password: ENC[AES256_GCM,data:X6sNxAo4aUE=,iv:EDGWdN2zEN1iaOjkSbdnuN7aF3DZdVI2a4srv04f7E0=,tag:Zbm4gIqz1YanzWnH16Qq0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL01qTHJTRFRkSXlSMGJs
        aEh4em0xaGpLRUxQc0w5T1phZUZnTlptS0IwCjNEUHhlSkxNWXRqVzNGd2s1eklE
        OWFSRlMyTC9xZkVEUU5STXA0dTR2MGcKLS0tIE80cGNhVVowTkhmb0FnUlBpTFNP
        STFKcFdjK09saS9qUmRhZDdieklMQ0kKAeH+ftdIBssxE9cYUwr7Qm4ArF9UztOR
        OpHb5mxwcMQEvfVs4/cBRmXUuJbP7Aeyqwj17SO1dkHsH7cesOfm6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1nurh0k74yrr98f0e03hnt9lx0c59la47umg7lmf774u6vyqup9dslhfkjh
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-13T20:15:51Z"
  mac: ENC[AES256_GCM,data:8ZD3WjaFYSxTKLiOS7RzZPDZ0afOw2JLAax6CyU/Y7cW+SYiCWWv+j9nQAIoW8ksQE4g/8kodZu4Cw1harkbx3U/P3drxxASRbxvaMpf6QUmtp1QPwv5KshcDXr1ZwD/AjMF56WifCsqwlz00r7+xB5ORUCzdZ7hXBa489Kon84=,iv:4ymSWqeM2JE8x8UPx7eAb/OBYGXOwz7ieQu48OlXks0=,tag:FvciDuiKlHtwvoEtrMsnxQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
